# Generated by Django 5.0.2 on 2024-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, null=True)),
                ('email', models.CharField(db_index=True, max_length=200, null=True)),
                ('password', models.CharField(db_index=True, max_length=100, null=True)),
            ],
        ),
    ]
