# Generated by Django 5.0.2 on 2024-02-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='rating',
            new_name='total_rating',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='rating',
            new_name='total_rating',
        ),
    ]
